config/routes.rb
Rails.application.routes.draw do

  root "sessions#new"
  post "/" => "sessions#create"
  get "sessions" => "sessions#new"
  post "sessions" => "sessions#create"
  get "signup" => "signup#new"
  post "signup" => "signup#create"
  get "endereco" => "endereco#new"
  post "endereco" => "endereco#create"
  get "exit" => "sessions#destroy"
  get "home" => "homes#new"
  get "vender" => "produtos#new"
  post "vender" => "produtos#create"
  get "anuncios" => "produtos#index"
  delete "produto" => "produtos#destroy"
  get "admin" => "homes#index"
  get "forgotpwd" => "forgotpwds#new"
  post "forgotpwd" => "forgotpwds#create"
  get "comprar" => "compras#new"
  get "busca" => "compras#index"
  put "comprar" => "compras#nova"
  get "detalhes" => "produtos#show"
  get "denuncia" => "denuncia#new"
  post "denuncia" => "denuncia#create"
  post "cancelar" => "produtos#edit"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compra.rb
class Compra < ApplicationRecord

end

app/models/denuncium.rb
class Denuncium < ApplicationRecord
end

app/models/endereco.rb
class Endereco < ApplicationRecord
end

app/models/forgotpwd.rb
class Forgotpwd < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
    belongs_to :user
    has_many :produtoimagem
    accepts_nested_attributes_for :produtoimagem
    mount_uploader :imagem, ImageUploader
end

app/models/produtoimagem.rb
class Produtoimagem < ApplicationRecord
    mount_uploader :imagem, ImageUploader
    belongs_to :produto
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
    has_secure_password
    has_many :produto
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, confirmation: true
    validates_length_of :password, minimum: 6
end

app/models/venda.rb
class Venda < ApplicationRecord
end

app/controllers/denuncia_controller.rb
class DenunciaController < ApplicationController
  before_action :set_denuncium, only: [:show, :edit, :update, :destroy]

  # GET /denuncia
  # GET /denuncia.json
  def index

  end

  # GET /denuncia/1
  # GET /denuncia/1.json
  def show
  end

  # GET /denuncia/new
  def new
    
    @produtoimagem = Produtoimagem.where(:produto_id => params[:id]).take

    @produto = Produto.where(:id => params[:id]).take
    
  end

  # GET /denuncia/1/edit
  def edit
  end

  # POST /denuncia
  # POST /denuncia.json
  def create
    @den = Denuncium.new(denuncium_params)
    @den.id_delator = cookies.signed[:user_id]
    
    if @den.save
      flash.now[:notice] = "Anúncio criado com sucesso!"
      redirect_to anuncios_path

    else
      flash.now[:notice] = "Ocorreu um problema, verifique os dados e tente novamente!"
      redirect_to home_path
    end
  end

  # PATCH/PUT /denuncia/1
  # PATCH/PUT /denuncia/1.json
  def update

  end

  # DELETE /denuncia/1
  # DELETE /denuncia/1.json
  def destroy
    @denuncium.destroy
    respond_to do |format|
      format.html { redirect_to denuncia_url, notice: 'Denuncium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_denuncium
      @denuncium = Denuncium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def denuncium_params
      params.require(:denuncia).permit(:idAnuncio, :desc)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes/new
  def new
    if (cookies[:user_id].blank?)
      redirect_to sessions_path
    end
  end
  

  # GET /homes/1/edit
  def edit
  end

  def index
    if ((cookies[:user_id].blank?) || (cookies[:user_level] != '50'))
      redirect_to exit_path, alert: "Você não tem permissão para acessar esta área! Faça login novamente."
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/denuncia_helper.rb
module DenunciaHelper
end

app/helpers/endereco_helper.rb
module EnderecoHelper
end

app/helpers/forgotpwds_helper.rb
module ForgotpwdsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/denuncia/_form.html.erb
<%= form_with(model: denuncium, local: true) do |form| %>
  <% if denuncium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(denuncium.errors.count, "error") %> prohibited this denuncium from being saved:</h2>

      <ul>
      <% denuncium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/denuncia/edit.html.erb
<h1>Editing Denuncium</h1>

<%= render 'form', denuncium: @denuncium %>

<%= link_to 'Show', @denuncium %> |
<%= link_to 'Back', denuncia_path %>

app/views/denuncia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Denuncia</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @denuncia.each do |denuncium| %>
      <tr>
        <td><%= link_to 'Show', denuncium %></td>
        <td><%= link_to 'Edit', edit_denuncium_path(denuncium) %></td>
        <td><%= link_to 'Destroy', denuncium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Denuncium', new_denuncium_path %>

app/views/denuncia/new.html.erb
<%= render "navbar/navbar"%>
<br><br><br><br>
<div class="container-fluid">
    <div class="row align-items-center justify-content-center">
        <div class="col-md-10 center-block">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-4">
                    <%= image_tag(@produtoimagem.imagem.mid.url) %>
                </div>
                <div class="col-md-8">
                    <div class="panel2 panel-default">
                        <div class="panel-body">
                            <p><strong>Título do anúncio: </strong><%= @produto.titulo %></p>
                            <%= bootstrap_form_for(:denuncia) do |f| %>
                                <%= f.text_area :desc, class: "input-lg", style: "height:180px;", maxlength: "499", label:"Descrição da denuncia", :required => true, :placeholder => "Descreva o motivo da denúncia..." %>
                                <%= f.hidden_field :idAnuncio, :value => params[:id] %>
                                <%= f.submit "Enviar", class: "btn btn-block btn-lg btn-danger-home active" %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<%= render "footer/footer2" %>

app/views/denuncia/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_denuncium_path(@denuncium) %> |
<%= link_to 'Back', denuncia_path %>