config/routes.rb
Rails.application.routes.draw do

  root "sessions#new"
  post "/" => "sessions#create"
  get "sessions" => "sessions#new"
  post "sessions" => "sessions#create"
  get "signup" => "signup#new"
  post "signup" => "signup#create"
  get "endereco" => "endereco#new"
  post "endereco" => "endereco#create"
  get "exit" => "sessions#destroy"
  get "home" => "homes#new"
  get "vender" => "produtos#new"
  post "vender" => "produtos#create"
  get "anuncios" => "produtos#index"
  delete "produto" => "produtos#destroy"
  get "admin" => "homes#index"
  get "forgotpwd" => "forgotpwds#new"
  post "forgotpwd" => "forgotpwds#create"
  get "comprar" => "compras#new"
  get "busca" => "compras#index"
  put "comprar" => "compras#nova"
  get "detalhes" => "produtos#show"
  get "denuncia" => "denuncia#new"
  post "denuncia" => "denuncia#create"
  post "cancelar" => "produtos#edit"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compra.rb
class Compra < ApplicationRecord

end

app/models/denuncium.rb
class Denuncium < ApplicationRecord
end

app/models/endereco.rb
class Endereco < ApplicationRecord
end

app/models/forgotpwd.rb
class Forgotpwd < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
    belongs_to :user
    has_many :produtoimagem
    accepts_nested_attributes_for :produtoimagem
    mount_uploader :imagem, ImageUploader
end

app/models/produtoimagem.rb
class Produtoimagem < ApplicationRecord
    mount_uploader :imagem, ImageUploader
    belongs_to :produto
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
    has_secure_password
    has_many :produto
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, confirmation: true
    validates_length_of :password, minimum: 6
end

app/models/venda.rb
class Venda < ApplicationRecord
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]
  def index
    @produto = Produto.where('titulo LIKE ? AND visivel = 1', "%#{params[:tituloBusc]}%").order('created_at DESC')
  end

  def nova
    @comprador = cookies.signed[:user_id]
    prod = Produto.where('id = ?', params[:idproduto]).take
    vendedor = prod.user_id
    sql = "INSERT INTO vendas(idcomprador,idvendedor,idproduto, estado) VALUES (#{@comprador}, #{vendedor},#{params[:idproduto]},0)"
    results = ActiveRecord::Base.connection.execute(sql)
    sql2 = "UPDATE produtos SET visivel = 0 WHERE id = #{params[:idproduto]}"
    results = ActiveRecord::Base.connection.execute(sql2)
    redirect_to comprar_path
  end

  private
  def set_compra
    @produto = Produto.find(params[:id])
  end

  def compras_params
    params.require(:compra).permit(:titulo)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes/new
  def new
    if (cookies[:user_id].blank?)
      redirect_to sessions_path
    end
  end
  

  # GET /homes/1/edit
  def edit
  end

  def index
    if ((cookies[:user_id].blank?) || (cookies[:user_level] != '50'))
      redirect_to exit_path, alert: "Você não tem permissão para acessar esta área! Faça login novamente."
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if (cookies[:user_id].blank?)
      redirect_to sessions_path
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nome, :email, :zap)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/denuncia_helper.rb
module DenunciaHelper
end

app/helpers/endereco_helper.rb
module EnderecoHelper
end

app/helpers/forgotpwds_helper.rb
module ForgotpwdsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/compras/_form.html.erb
<%= form_with(model: compra, local: true) do |form| %>
  <% if compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Show', @compra %> |
<%= link_to 'Back', compras_path %>

app/views/compras/index.html.erb
<%= render "navbar/navbar" %>
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-md-12">
        <h2 style="color:black; font-family: Harabara Mais, Helvetica, sans-serif; margin-top: 20px;">Resultados da busca</h2>
            <div class="panel panel-default" style="margin-top: 25px;">
                <div class = "panel-body">
                    <table class="table table-striped table-hover table-sm">
                        <thead>
                            <tr>
                                <th style = "color: black;">
                                    <%= image_tag "camera.png", size: "25x20", style: "margin-left: 35px;"  %>
                                </th>
                                <th style = "color: black;">
                                    Título
                                </th>
                                <th style = "color: black;">
                                    Autores
                                </th>
                                <th style = "color: black;">
                                    Data de Publicação
                                </th>
                                <th style = "color: black;">
                                    Ações
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @produto.each do |produto| %>   
                            <% Produtoimagem.where(:produto_id => produto.id).find do |image| %>
                            <tr>
                                    <td style="width: 20%; word-wrap: break-word;"><%= image_tag(image.imagem.thumb.url) %></td>
                                    <td style="width: 30%; word-wrap: break-word;"><%= produto.titulo %></td>
                                    <td style="width: 15%; word-wrap: break-word;"><%= produto.autores %></td>
                                    <td style="width: 10%; word-wrap: break-word;"><%= produto.data_pub %></td>
                                    <td style="width: 10%; word-wrap: break-word;">
                                        <%= link_to 'Tenho interesse', 
                                        {:controller=>:compras,:action=>:nova, :idproduto=>produto.id}, 
                                        method: :put, data: { confirm: 'Você tem certeza disso?' }, class: "btn btn-sm btn-block btn-danger-home", style: 'color: #FFFFFF;', :remote => true %>
                                        <br>
                                        <%= link_to 'Denunciar publicação', {:controller=>:denuncia, :action => :new, :id =>produto.id}, 
                                        method: :get, data: { confirm: 'Você tem certeza disso?' }, class: "btn btn-sm btn-block btn-danger-home", style: 'color: #FFFFFF;' %>
                                    </td>
                                </tr>
                            <% end %>
                            <% end %>
                        </tbody>
                    </table>
                    <%= link_to "Voltar", comprar_path, class:"btn btn-sm btn-danger-home active" %>
                    <p id="notice"><%= notice %></p>
                </div>
            </div>
		</div>
	</div>
</div>
<br>
<%= render "footer/footer2" %>

app/views/compras/new.html.erb
<%= render "navbar/navbar" %>
<div class="container-fluid h-100">
  <br><br><br><br>
  <div class="row justify-content-center h-100">
    <div class="col-sm-6" style="margin-top: auto; margin-bottom:auto;">
      <div class="panel panel-default" style="display:table; position:absolute; width: 100%; height: auto;">
        <div class="panel-body">
          <%= bootstrap_form_tag url: '/busca', method: :get do |f| %>
          <%= f.text_field :tituloBusc, name: "tituloBusc", label: "Título da publicação", placeholder: 'O que você procura?' %>
          <%= f.submit "Buscar", class: "btn btn-block btn-lg btn-danger-home active" %>
        <% end %>
        <p id="notice"><%= notice %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<%= render "footer/footer2" %>

app/views/compras/show.html.erb
<%= render "navbar/navbar"%>
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-md-12">
        <h2 style="color:; font-family: Harabara Mais, Helvetica, sans-serif; margin-top: 20px;">Resultados da busca</h2>
            <div class="panel panel-default" style="margin-top: 25px;">
                <div class = "panel-body">
                    <table class="table table-striped table-hover table-sm">
                        <thead>
                            
                        </thead>
                        <tbody>
                           
                        </tbody>
                    </table>
                    <%= link_to "Voltar", home_path, class:"btn btn-sm btn-danger-home active" %>
                    <%=  %>
                </div>
            </div>
		</div>
	</div>
</div>